#!/bin/bash

# QUICK START DEPLOYMENT GUIDE
# =========================================

echo "╔══════════════════════════════════════════════════════════╗"
echo "║   AI Medical Image Generator - Deployment Options       ║"
echo "╚══════════════════════════════════════════════════════════╝"
echo ""

echo "Choose a deployment method:"
echo ""
echo "1. 🚀 ngrok (Quick Demo - 2 minutes)"
echo "   - Instant public URL"
echo "   - Perfect for testing/sharing"
echo "   - Run: ./deploy-ngrok.sh"
echo ""

echo "2. 🌐 Render.com (Production - 15 minutes)"
echo "   - Free tier available"
echo "   - Auto-deploy from Git"
echo "   - Permanent URL with SSL"
echo "   - Steps:"
echo "     a. Push to GitHub"
echo "     b. Connect at render.com"
echo "     c. Add environment variables"
echo ""

echo "3. 🚂 Railway.app (Production Alternative - 10 minutes)"
echo "   - Similar to Render"
echo "   - Generous free tier"
echo "   - Easy GitHub integration"
echo "   - Steps:"
echo "     a. Push to GitHub"
echo "     b. Import at railway.app"
echo "     c. Add environment variables"
echo ""

echo "4. 🐍 PythonAnywhere (Python-focused - 20 minutes)"
echo "   - Python-specific hosting"
echo "   - Web-based file upload"
echo "   - Free tier available"
echo ""

echo "5. 💻 VPS (Full Control - 1 hour)"
echo "   - DigitalOcean, Linode, AWS, etc."
echo "   - Complete control"
echo "   - Custom domain easy"
echo "   - Requires server management"
echo ""

echo "════════════════════════════════════════════════════════════"
echo ""
echo "📚 Full deployment guide: See DEPLOYMENT.md"
echo ""
echo "🔑 Required API Keys:"
echo "   - OPENAI_API_KEY (for prompt generation)"
echo "   - GOOGLE_GENERATIVE_AI_API_KEY (for image generation)"
echo ""

read -p "Press Enter to see recommended quick start..."
echo ""

echo "══════════════════════════════════════════════════════════"
echo "✨ RECOMMENDED QUICK START (ngrok)"
echo "══════════════════════════════════════════════════════════"
echo ""
echo "1. Install ngrok (if not installed):"
echo "   brew install ngrok"
echo ""
echo "2. Set API keys:"
echo "   export OPENAI_API_KEY='your-key'"
echo "   export GOOGLE_GENERATIVE_AI_API_KEY='your-key'"
echo ""
echo "3. Run deployment:"
echo "   ./deploy-ngrok.sh"
echo ""
echo "4. Share the ngrok URL with users!"
echo ""
echo "══════════════════════════════════════════════════════════"
